### ISSUE TITLE
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by s1n7ax** [dcampos/nvim-snippy#1]
```lua
use {'dcampos/snippy'}
```

Packer shows following error.
```
 ✗ Failed to install dcampos/snippy
  Errors:
    Cloning into '/home/s1n7ax/.local/share/nvim/site/pack/packer/start/snippy'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

However, `cmp-snippy` installs without any issue.

**Comment by markdestouches** [comment]
I have the same problem. What is the solution?

**Comment by dcampos** [comment]
@markdestouches There was a mistake in the README. It should be `dcampos/nvim-snippy` instead of `dcampos/snippy`:

```lua
use {'dcampos/snippy'}
```

I've fixed the README.

**Comment by s1n7ax** [comment]
lol. I thought I typed it wrong. I probably copied it from the readme then.
