### ISSUE TITLE
Cut text expansion clobbers the clipboard registers "* and "+

### ISSUE THREAD

**Issue by msprev** [dcampos/nvim-snippy#104]
### Description

Cut text snippet expansion silently replaces the contents of clipboard registers `"*` and `"+` with the contents of the unnamed register `""`. Contents of  registers `"*` and `"+` are lost forever.

### Steps to Reproduce

1. With `set clipboard = unnnamed` or `unnamedplus`
2. Copy text to the system clipboard in another application (e.g. copy a url from Google chrome)
3. Inside neovim, select some text and perform a cut text snippet expansion

### Expected Result

Contents of registers`"*` and `"+` should be restored after expansion. Or at least, they should not be lost forever.

### Actual Result

Clipboard contents `"*` and `"+` are silently erased and replaced with what was previously held in register `""`

**Comment by msprev** [comment]
Note that having the contents of `"*` and `"+` accessible inside a snippet is also useful. A snippet might want to paste what is currently sitting in the system clipboard as part of an expansion.

**Comment by dcampos** [comment]
Good point. We could use another register for that, like `"a`,  as it wouldn't clobber `"*` or `"+`, and restore it after cutting the text. I'm open to suggestions.

**Comment by msprev** [comment]
Thanks, I like the idea of using another register like inside the snippet. Or, possibly assigning a snippy variable that could be accessible to snippet writers with the clipboard contents -- that way `"a` wouldn't get clobbered. 

I would like to write a snippet that creates a markdown link and automatically inserts a url in the appropriate place if one is sitting in the clipboard (TextMate used to behave like this).

**Comment by dcampos** [comment]
The issue of clobbering should be fixed now. I decided to use "x instead of "" for storing the selection temporarily, restoring its previous content afterwards. This should eliminate any clobbering, although a refactor to avoid using any registers at all would be very welcome in the future.
