### ISSUE TITLE
Very slow input after triggering/expanding a snippet since 5e2682d

### ISSUE THREAD

**Issue by oedotme** [dcampos/nvim-snippy#118]
### Description

Since 5e2682d, triggering/expanding a snippet causes a slow down in the nvim input in general. 

### Steps to Reproduce

1. Edit a file `test.tsx`
2. Insert some code `console.log('this is a test')`
3. Trigger a snippet
4. Try inserting the same code again

### Expected Result

To continue editing text without lag.

Pinning the previous commit ee3b830 makes it work as expected.

### Actual Result

Very noticeable lag in general afterwards triggering a snippet.

### Additional Context

Config with `lazy`:

```lua
{
  'https://github.com/dcampos/nvim-snippy',
  event = 'VeryLazy',
  opts = {
    snippet_dirs = '~/.config/nvim/snippets',
    mappings = {
      is = { ['<c-n>'] = 'expand_or_advance', ['<c-p>'] = 'previous' },
      nx = { ['<leader>x'] = 'cut_text' },
    },
  },
}
```

<br>

Config with `cmp`:

```lua
cmp.setup({
  ...,
  snippet = {
    expand = function(args) snippy.expand_snippet(args.body) end,
  },
})
```

<br>

Recording (second line triggers a snippet, third line lagging noticeably):

https://github.com/dcampos/nvim-snippy/assets/20151138/9a3bb300-3464-4708-8439-d7a9e4ade551

Having the sound of the video on could help visualizing the lag.

**Comment by DrGo** [comment]
I am noticing lag as well. I am on 83a6ee5

**Comment by dcampos** [comment]
Thanks for reporting. Calling `cmp.visible()` seems to [cause input delay](https://github.com/hrsh7th/nvim-cmp/issues/1613). I've reverted the offending commit, let's hope there's another way to check whether the custom menu used by cmp is visible.

**Comment by DrGo** [comment]
Thanks for the quick action and for all you do to maintain this helpful plugin

**Comment by oedotme** [comment]
Thanks a lot @dcampos! I'll close this issue as it's now resolved with the revert.
