### ISSUE TITLE
'rand  (m1 not expanding

### ISSUE THREAD

**Issue by MarcWeber** [dcampos/nvim-snippy#119]
### Description

The completion shows m1 and rand. But when using manual trigger snippet rand or snippet m1 are not found after ' or (.
Must have something to do with word_bound=false in main.lua
Cause the 'rand rand and nd d are tried.

In test cases I found snippet word ".." also failed (?)

Is this expected behavior?

### Steps to Reproduce

Try _.snippets

```
snippet rand
	R`rand()`
````

open a file and try 'rand and then 

```
    imap <expr> <c-Tab> snippy#can_expand_or_advance() ? '<Plug>(snippy-expand-or-advance)' : '<Tab>'
    smap <expr> <c-tab> snippy#can_jump(1) ? '<Plug>(snippy-next)' : '<Tab>'
```
and it fails. if you add space before rand it works.

Similar can happen before ) or such.
However cmp-snippy shows them.

### Expected Result

'rand to expand rand to Rxxxx

### Actual Result

no expansion happening

**Comment by dcampos** [comment]
> Is this expected behavior?

I believe so. See [this issue](#53) for more information on the current behavior. For getting the behavior you want to achieve, you could try the `i` (in word) or `w` (just considers `iskeyword` characters) snippet options (see `:help snippy-snippet-options` for more info, although the docs are currently wrong when they say `w` is the default behavior).

**Comment by dcampos** [comment]
One of our goals here is to keep compatibility with other snippet engines, specially SnipMate and, concerning snippet options, with Ultisnips. So I've done some testing and found out that Ultisnips does consider only word characters by default. Consequently, my previous conclusion in [13](13) was incorrect.  Snipmate and Luasnip follow the same behavior.

So, I believe our current behavior of considering WORD (space-delimited) trigger by default is a bug that needs fixing.

Regarding cmp-snippy, it doesn't do anything smart at the moment, just sends all available snippets in the current scope to cmp.

**Comment by MarcWeber** [comment]
To be honest a snippet engine should be useful.
So if you can make this regex an option users can fix in their config:

        local word = current_line_to_col:match('(%S*)$') -- Remove leading whitespace
        local word = current_line_to_col:match('([%w_]*)$') -- Remove leading whitespace


By useful I mean any foo().u<expand> the . or ) are word boundaries in almost all programming languages. So changing the default behaviour e.g. that way
makes this plugin much more fun to use for me. Because in word expannsion eg u -> use() in PHP doesn't make sense as 'in word'.

So thinking about how to define a word boundary (maybe per filetype) or such actually could make sense and fix this kind of issue.

I somehow agree that having standards makes sense.
So the question turns more what's the right place to discuss this ?
Cause there are more ideas like what about snippets including both
1) import annotations
2) library dependencies? (eg for JS package.json)
