### ISSUE TITLE
Incompatibility with nvim-lspconfig?

### ISSUE THREAD

**Issue by telemachus** [dcampos/nvim-snippy#131]
### Description

I recently noticed that nvim-snippy does not work when a language server is running. (I'm using nvim-lspconfig to configure language servers, but I'm not sure whether nvim-lspconfig itself is part of the problem.) In the past, I had used nvim-snippy and language servers together without trouble, but today I went to edit a go file and realized no snippets worked there. I then checked on a lua file, and I had the same problem. By contrast, snippets still worked fine for markdown and json files where I don't use a language server. In addition, if I stop loading go or lua language servers, then nvim-snippy expands snippets as expected.

### Steps to Reproduce

1. Start a language server for some language and then try to use snippets for that language using nvim-snippy.

### Expected Result

Snippets should expand

### Actual Result

Snippets are not picked up. (The mappings for nvim-snippy are still present, but no snippets expand.)

### Additional Context

`$XDG_CONFIG_HOME/nvim/init.lua`:

```lua
local lspconfig = require("lspconfig")
lspconfig.gopls.setup({})

require("snippy").setup({
    mappings = {
        is = {
            ["<Tab>"] = "expand_or_advance",
            ["<S-Tab>"] = "previous",
        },
        nx = {
            ["<leader>x"] = "cut_text",
        },
    },
})
```

`$XDG_CONFIG_HOME/nvim/snippets/snippets.go`:

```
# package {main}
snippet pkg "package {main}"
	package ${1:main}
# shorthand variable declaration
snippet : "v := value" b
	$1 := $2
# main()
snippet main "func main() { ... }" b
	func main() {
		${1}
	}${0}
# End of snippets

# vim:ft=snippets:
```

`nvim --version`:

```
nvim --version
NVIM v0.10.0-dev-2543+gade1b12f4
Build type: Release
LuaJIT 2.1.1707061634
```

For what it's worth, I noticed this problem on nvim nightly (as listed above), but I just downgraded to v0.9.5, and I have the same results.

**Comment by rickalex21** [comment]
I'm having problems with nighly/stable, but I'm new to snippy so not sure if I'm using the correct config or
it has something to do with this issue. I also disabled luasnip. I am using LazyVim:

lua/plugins/snippy.lua

```lua
return {
  "dcampos/nvim-snippy",
  -- lazy = false,
  -- priority = 1312,
  opts = {
    snippet_dirs = "~/.config/nvim-lazyvim/snippets" ,
    hl_group = "Comment",
    mappings = {
      is = {
        ["<c-l>"] = "expand_or_advance",
        ["<c-j>"] = "next",
        ["<c-k>"] = "previous",
      },
    },
  },
}


-- return {
--   "dcampos/nvim-snippy",
--   -- enabled = false,
--   --
--   dependecies = {"dcampos/cmp-snippy"},
--   config = {
--     function()
--       require("snippy").setup({
--         mappings = {
--           is = {
--             ["<Tab>"] = "expand_or_advance",
--             ["<S-Tab>"] = "previous",
--           },
--           nx = {
--             ["<leader>x"] = "cut_text",
--           },
--         },
--       })
--     end,
--   },
-- }
--
```

Snippets file snippets/all.snippets

```text
# Comments are possible
snippet fun
	function ${1:name}(${2:params})
		${0:$VISUAL}
	end
snippet upcase
	local ${1:var} = '${1/.*/\U\0/g}'
snippet choices
	print('My favorite language is: ${1|JavaScript,Lua,Rust|}')
snippet date
	Current date is `strftime('%c')`
# Custom tabstop order
snippet repeat
	repeat
		${2:what}
	while ${1:condition}
snippet afaik
	repeat
		${2:what}
	while ${1:condition}
```

**Comment by telemachus** [comment]
@rickalex21 Two questions: (1) Are you only having problems for languages where you have a language server running? (2) If you haven't already, can you try snippets for a language without a language server attached?

**Comment by telemachus** [comment]
If you can't get snippets working at all, then I don't think that's related to this issue. You should probably open a separate issue.

> In snippy/all I have all.snippets.

I don't think that nvim-snippy supports `all.snippets`. Remove the `all` directory, and change that filename to `_.snippets`. See if that works.

> I do have Ultisnips enabled, I can't disable it

I'm not sure whether you can have two snippets plugins at the same time. I suppose that depends on mappings, maybe.

**Comment by rickalex21** [comment]
@telemachus  Thanks for your help that was it. Will need to figure out a way to allow the all or 
just live with the "_". Gonna mess with it tomorrow. Luasnip has something like this:

```lua
require("luasnip").filetype_extend("all", { "_" })
```

About your issue I could not reproduce, I have the LSP running with lua and I am able to
expand snippets with both : NVIM v0.10.0-dev-2507+g3df1211eb and NVIM v0.9.5.

The only thing I cant do is view the snippets yet but that's on me will need to configure cmp.

**Comment by telemachus** [comment]
> About your issue I could not reproduce, I have the LSP running with lua and I am able to expand snippets with both : NVIM v0.10.0-dev-2507+g3df1211eb and NVIM v0.9.5.

Ah, that's helpful information: thanks. I'll try to track down my problem and update this issue as soon as I can.

> The only thing I cant do is view the snippets yet but that's on me will need to configure cmp.

As I recall, you have to install a separate repo (https://github.com/dcampos/cmp-snippy) and then hook that up to get cmp support. I don't use that, so I don't know all the details. But start by looking at the README for cmp-snippy. Good luck.

**Comment by rickalex21** [comment]
@telemachus  I don't use Ultisnips in LazyVim and I disabled luasnip just to make sure no snippets were running.
I think maybe a plugin could have been updated and messed things up. Try using a minimal config or
better yet use LazyVim to see if you can reproduce. For me it's working on LazyVim both nightly and
stable nvim. Here is how you can reproduce:

Go to [LazyVim Instllation](https://www.lazyvim.org/installation) you can clone it to `~/.config/nvim-lazyvim` if you want. You can do what I do and set your `NVIM_APPNAME` variable to `nvim-lazyvim` so you can use the
new configuration.

Once you are setup with the lazyvim configuration, enable vim-snippy by creating a file:

```lua
-- ~/.config/nvim-lazyvim/lua/plugins/snippy.lua
return {
  "dcampos/nvim-snippy",
  -- enabled = false,
  -- lazy = false,
  -- priority = 1312,
  opts = {
    snippet_dirs = "~/.config/nvim-lazyvim/snippets",
    hl_group = "Comment",
    mappings = {
      is = {
        ["<c-l>"] = "expand_or_advance",
        ["<c-j>"] = "next",
        ["<c-k>"] = "previous",
      },
    },
  },
}
```

Create a unique snippet:

```txt
# ~/.config/nvim-lazyvim/snippets/_.snippets
snippet uniquesnip
	Do <c-l> to expand me.
```

You probably don't need to disable luasnip but you can if you want:

```lua
-- ~/.config/nvim-lazyvim/lua/plugins/luasnip.lua
return {
{ "L3MON4D3/LuaSnip", enabled = false },

}
```

You should now have an enviroment where you can test nvim-snippy with lsp.
I use fish shell but for bash you do `export NVIM_APPNAME="nvim-lazyvim"`

```fish
set -x NVIM_APPNAME nvim-lazyvim
/usr/local/bin/nvim-nightly
```

I use Linux, make changes accordingly. Let me know how things go and if you need help.

**Comment by telemachus** [comment]
Thanks for the suggestions. I prefer not to work with a distro, but I will try a clean install and minimal init.lua and report back.

**Comment by telemachus** [comment]
I found the problem (it was in my `init.lua` file), and I'll close this now. Sorry for the noise. @rickalex21, thanks for helping me rubber duck this.
