### ISSUE TITLE
.h files are assumed C++ and not C

### ISSUE THREAD

**Issue by engywook** [dcampos/nvim-snippy#138]
### Description

It seems .h files are assumed to be C++ headers and not C headers.

I got around the issue by symlinking my c.snippets to cpp.snippets

### Steps to Reproduce

1 Only have c.snippets
2 try expanding a snippet in a header file, like test.h, it doesn't work
3 :SnippyEdit opens empty cpp.snippets

### Expected Result

Expanded C snippet in header file

### Actual Result

Snippet is not expanded

**Comment by dcampos** [comment]
Snippy relies entirely on Neovim's detection of the current filetype, so I believe Neovim treats header files as C++ files by default. After some Googling, it appears this is indeed the case. See [this Reddit post](https://www.reddit.com/r/neovim/comments/dung7s/neovim_recognizes_c_h_files_as_c_syntax_files/) for reference.

You can also refer to `h: c_syntax_for_h`.
