### ISSUE TITLE
Selection is always one character short

### ISSUE THREAD

**Issue by roylez** [dcampos/nvim-snippy#143]
### Description

I track it down to this line. Shouldn't it be `to[2] + 1` as well?

https://github.com/dcampos/nvim-snippy/blob/86a0b645551ca83153a594097ee0267498abaae2/lua/snippy/main.lua#L50

### Steps to Reproduce

I am not sure if this is my nvim behave differently or a problem caused by my configuration. But this should be reproducible by creating snippets with placeholder texts.

### Expected Result

The last character of placeholder text should not be cut off.

### Actual Result

![screenshot 2024 12 12 0946](https://github.com/user-attachments/assets/0493abcf-df41-45ea-a7d7-2cc80e293ae7)

**Comment by dcampos** [comment]
Thanks for reporting the issue. I believe it has something to do with the `selection=exclusive` Neovim option. Can you please confirm that you have `selection=exclusive` set? You can run `:set selection` and check the value.

If your selections is indeed set to exclusive, as a workaround, you may set it to `inclusive` (which is the default). Nevertheless, I think Snippy should be fixed to take that option's value into consideration.

**Comment by roylez** [comment]
Indeed I have `selection=exclusive` set as I did not want delete EOL by mistake too often.

**Comment by dcampos** [comment]
Should be fixed now. Please let me know if something still doesn't work for you.
