### ISSUE TITLE
The choice menu doesn't close when I jump to the beginning of line.

### ISSUE THREAD

**Issue by uga-rosa** [dcampos/nvim-snippy#23]
If it's the same line, choice menu will close.

![snippy](https://user-images.githubusercontent.com/82267684/140247762-569335ee-3463-4b3d-9708-46b05030b22a.gif)

**Comment by uga-rosa** [comment]
It's when you jump to the next line, or rather the beginning of the line.

**Comment by dcampos** [comment]
Thanks for reporting. I think my latest should fix it. Can you confirm that it works for you now?

**Comment by uga-rosa** [comment]
work fine! thx!
