### ISSUE TITLE
Error E5108

### ISSUE THREAD

**Issue by Moukubi** [dcampos/nvim-snippy#24]
An error appear while delete a line which just snippy completed.
`E5108: Error executing lua ...m/site/pack/packer/start/nvim-snippy/lua/snippy/stop.lua:32: attempt to index a nil value`

**Comment by dcampos** [comment]
Thanks for reporting. I tried but couldn't reproduce the error. Could you provide the steps to reproduce it?

**Comment by Moukubi** [comment]
Emm, i can't reproduce this error either.
I thought about it again, this error occured maybe related to the command `PackerUpate` failed I executed yesterday.

Thank you for this plugin and replying. It works very well for me now.

**Comment by Moukubi** [comment]
OK, run into this issue again.

**environment**: 
Linux Blue 5.15.0-2-amd64 #1 SMP Debian 5.15.5-2 (2021-12-18) x86_64 GNU/Linux
xfce4-terminal/unstable,now 0.8.10-1 
bash/unstable,now 5.1-6 amd64
NVIM v0.6.1-3
Build type: Release
LuaJIT 2.1.0-beta3

**reproduce**:
1. expand `fori` snippet in lua file and "snippy-expand-or-advance" to `--body` part
```
for i,v in ipairs(table_name) do
     -- body                               <----  here          
end 
```
2. press `ESC` to back to normal mode and press dj to delete last two lines.

**TIPS**: only occurs in `Plug 'honza/vim-snippets'` snippets, other snippets file works well.

**Error report**: 
E5108: Error executing lua ...m/site/pack/packer/start/nvim-snippy/lua/snippy/st
op.lua:30: attempt to index a nil value
stack traceback:
        ...m/site/pack/packer/start/nvim-snippy/lua/snippy/stop.lua:30: in funct
ion 'get_text'
        ...e/nvim/site/pack/packer/start/nvim-snippy/lua/snippy.lua:88: in funct
ion 'mirror_stop'
        ...e/nvim/site/pack/packer/start/nvim-snippy/lua/snippy.lua:325: in func
tion '_mirror_stops'
        ...e/nvim/site/pack/packer/start/nvim-snippy/lua/snippy.lua:220: in func
tion '_handle_TextChanged'
        [string ":lua"]:1: in main chunk

**Comment by dcampos** [comment]
@Moukubi Thanks for the details. This time I was able to reproduce the error by following the steps you provided and using `nvim --clean -u minimal.vim' with the minimal config:

https://github.com/dcampos/nvim-snippy/blob/master/misc/minimal.vim

It only occurs if the cursor ends up in a valid snippet position after the deletion.

**Comment by dcampos** [comment]
I think I've found a way to prevent the error from happening.
