### ISSUE TITLE
Highlights are wrong.

### ISSUE THREAD

**Issue by uga-rosa** [dcampos/nvim-snippy#27]
![image](https://user-images.githubusercontent.com/82267684/141284758-1dad755e-8b97-4ae1-bb78-2d311787f16b.png)

`echo expand("%:t")` -> `go.snippets`
`set ft?` -> `filetype=snippets`
`setlocal syntax?` -> `syntax=snippets`

**Comment by dcampos** [comment]
It should be fixed now. Thanks again!
