### ISSUE TITLE
Better documentation suggestions

### ISSUE THREAD

**Issue by moshiur-raj** [dcampos/nvim-snippy#33]
I think the doc man be a bit clearer on some topics. For example, snippet_dirs is the directory containing the snippets folder. This one caused me a lot of headache as I thought snippet files had to be in snippet_dirs. Also you should mention that snippet definitions have to indented using tab. Thanks for the plugin btw. It's simple and it works like a charm.

**Comment by dcampos** [comment]
Hi, thanks for the suggestions. The `snippet_dirs` behaviour you described is indeed confusing, maybe it should be changed to not require a nested snippets folder. I'll give it some thought.

> Also you should mention that snippet definitions have to indented using tab.

Actually, it should no longer be necessary to use tabs, indenting with spaces should be possible, which is also not documented yet. Syntax highlighting seems to be broken currently if definitions are indented with spaces.

**Comment by dcampos** [comment]
I decided to change the `snippet_dirs` behavior. Now it's no longer necessary to create a nested `snippets/` folder. Please move your snippets to the top-level directory after updating Snippy.

The documentation was also expanded and now should cover your suggested topics. Syntax highlighting for space-indented snippets has been fixed too.

**Comment by moshiur-raj** [comment]
@dcampos Thank you.
