### ISSUE TITLE
Trigger options similar to UltiSnips

### ISSUE THREAD

**Issue by paniash** [dcampos/nvim-snippy#35]
Hi!

I was wondering if like UltiSnips, nvim-snippy has options for triggers. For example, in UltiSnips

```snippets
snippet ss1 "Subsection*" A
\subsection*{$1}

$0
endsnippet
```

would mean that typing `ss1` would instantly place the template without pressing `<Tab>` (`A` in the first line means automatic). Is this sort of thing possible with nvim-snippy?

**Comment by dcampos** [comment]
Hi, thanks for trying out Snippy.

> I was wondering if like UltiSnips, nvim-snippy has options for triggers.

There is no support for UltiSnips-style auto-trigger at the moment. It sounds like a nice feature to have and also not too difficult to implement. I might try to implement it in the future if someone else doesn't in the meantime.

**Comment by paniash** [comment]
@dcampos Thank you! Unfortunately, my workflow requires auto-triggers along with other options that come with UltiSnips, my main reason for switching being responsiveness/speed purposes. Hopefully, the feature gets implemented soon into snippy. :-)

**Comment by AurelWeinhold** [comment]
Hi!

What about the other trigger options? Namely the options for when to expand:
`b` for beginning of the line,
`w` on word boundary,
`i` inside word, (this one especially)
`r` expand on a regexp (probably not simple and probably not necessary at first).

This is currently the only thing holding me back from using snippy over ultisnips, so I would really appreciate those being implemented!

**Comment by paniash** [comment]
@AurelWeinhold Hi! I wasn't aware of options other than `A` and `b`. Thanks!
Although, I highly doubt these trigger options are implemented in snippy. @dcampos would know better.

**Comment by dcampos** [comment]
The autotrigger feature has been implemented.
