### ISSUE TITLE
Unfinished snippet breaks input after saving file

### ISSUE THREAD

**Issue by danilshvalov** [dcampos/nvim-snippy#39]
Hey! Thank you for a really nice plugin. I hope your plugin will be popular.

I found a small bug in your plugin. I hope it won't be difficult to fix.

https://user-images.githubusercontent.com/57654917/148419978-063bbd20-8ee0-47dc-bbd4-800e08fb9e62.mov

**Comment by dcampos** [comment]
> Hey! Thank you for a really nice plugin. I hope your plugin will be popular.

Hi! Thanks for the kind words.

> I found a small bug in your plugin. I hope it won't be difficult to fix.

I tried but couldn't reproduce the problem by saving a file with an unfinished snippet. Maybe it's a conflict with another plugin, or something that occurs only in very specific conditions.

Could you check if it can be reproduced using the minimal config below?

<details>
<summary>Minimal config</summary>

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'dcampos/nvim-snippy'
Plug 'honza/vim-snippets'
call plug#end()
PlugInstall | quit

imap <expr> <Tab> snippy#can_expand_or_advance() ? '<Plug>(snippy-expand-or-next)' : '<Tab>'
imap <expr> <S-Tab> snippy#can_jump(-1) ? '<Plug>(snippy-previous)' : '<Tab>'
smap <expr> <Tab> snippy#can_jump(1) ? '<Plug>(snippy-next)' : '<Tab>'
smap <expr> <S-Tab> snippy#can_jump(-1) ? '<Plug>(snippy-previous)' : '<Tab>'
xmap <Tab> <Plug>(snippy-cut-text)

lua << EOF

EOF
```

</details>

**Comment by danilshvalov** [comment]
I found the reason. The error occurs when using formatter. For example, when I use [`formatter.nvim`](https://github.com/mhartington/formatter.nvim) or [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig/) this happens.

**Comment by dcampos** [comment]
Snippy uses extmarks to track tabstop/placeholder positions, so any plugin that changes the entire content of the buffer will cause issues, because AFAIK the existing extmarks will be then moved or destroyed (I didn't test this yet, so don't know the exact behavior).

I think the best way to fix this would be to find a way to detect the buffer change and clear the snippet state.

**Comment by danilshvalov** [comment]
Maybe change `check_position` function?

<details>
<summary>Code</summary>

```lua
function M._check_position()
    local stops = buf.stops
    local row, col = unpack(api.nvim_win_get_cursor(0))
    row = row - 1
    local ranges = {}
    
    -- add this
    local max_row = vim.api.nvim_buf_line_count(0) - 1
    local max_col = fn.col('$') - 1
    --

    for _, stop in ipairs(stops) do
        local from, to = stop:get_range()
        table.insert(ranges, { from, to })
        local startrow, startcol = unpack(from)
        local endrow, endcol = unpack(to)
        if fn.mode() == 'n' then
            if startcol + 1 == fn.col('$') then
                startcol = startcol - 1
            end
            if endcol + 1 == fn.col('$') then
                endcol = endcol - 1
            end
        end

       -- add this
        if startrow > max_row or startcol > max_col or endrow > max_row or endcol > max_col then
            print(startrow, startcol, endrow, endcol, max_row, max_col)
            return buf.clear_state()
        end
       --

        if
            (startrow < row or (startrow == row and startcol <= col))
            and (endrow > row or (endrow == row and endcol >= col))
        then
            return
        end
    end
    buf.clear_state()
end
```
</details>

**Comment by dcampos** [comment]
> Maybe change check_position function?

That may work. Could you try the fix-39 branch (#40)?

I'm still not able to reproduce the error, but I can confirm that the formatter.nvim plug-in changes the extmarks ranges.

**Comment by danilshvalov** [comment]
The problem is gone. Thank you very much.

**Comment by dcampos** [comment]
Nice! Thanks for the feedback. I'll go ahead and merge the PR.
