### ISSUE TITLE
Cannot undo repeated placeholders

### ISSUE THREAD

**Issue by mg979** [dcampos/nvim-snippy#43]
The undo history gets really messed up with repeated placeholders.

Example lua snippet:

```
snippet for
	for ${1:k,v} in pairs(${2:table}) do
		${3:code}
		${3}
	done
```

After editing the third placeholder, pressing `u` repeatedly will only undo last edit.

**Comment by mg979** [comment]
I could fix it by changing https://github.com/dcampos/nvim-snippy/blob/307d29140676b450c55c2f8eb4a2abfbc94c497b/lua/snippy/stop.lua#L35-L43

to

```lua
local last_text

function Stop:set_text(text)
    local startpos, endpos = self:get_range()
    if self.spec.transform then
        local transform = self.spec.transform
        text = fn.substitute(text, transform.regex.raw, transform.format.raw, transform.flags)
    end
    if last_text and text == last_text then
      return
    end
    last_text = text
    local lines = vim.split(text, '\n', true)
    api.nvim_buf_set_text(0, startpos[1], startpos[2], endpos[1], endpos[2], lines)
end
```

Maybe you can find a better solution.

The problem seems to be that when insert mode is exited, the snippet still tracks changes, including undos, and updates the text again.

**Comment by dcampos** [comment]
Hi! Thanks for narrowing down the problem and also for helping out with a solution. I was already working on a fix before reading your comment, but your solution seems to be as good as the one I came up with.

**Comment by mg979** [comment]
If this can only happen after undo, this would be maybe better, because snippet state should be cleared.

https://github.com/dcampos/nvim-snippy/blob/51dda3fe31d38dff045b917d05e585234de94283/lua/snippy.lua#L82

```lua
local function did_undo()
    local ut = fn.undotree()
    return ut.seq_last ~= ut.seq_cur
end

local function mirror_stop(number)
    if did_undo() then
        buf.clear_state()
        return
    end
    local stops = buf.stops
    if number < 1 or number > #stops then
        return
    end
    local value = stops[number]
    local text = value:get_text()
    for i, stop in ipairs(stops) do
        if i > number and stop.id == value.id then
            stop:set_text(text)
        end
    end
    if value.spec.type == 'placeholder' then
        if text ~= value.placeholder then
            buf.clear_children(number)
        end
    end
end
```

**Comment by dcampos** [comment]
Good point. I think in most cases the snippet state being cleared wouldn't be a problem, but the user might just want to undo some mistake and then re-enter insert mode and jump to the next tabstop. So I'm not really sure about this.
