### ISSUE TITLE
`snippy-cut-text` mapped to `<C-i>` without explicit mapping

### ISSUE THREAD

**Issue by AurelWeinhold** [dcampos/nvim-snippy#46]
Hi!

First of, thank you again for this great plugin. I really enjoy using it!

I noticed `<C-i>` was not working in my neovim configuration and when I started to investigate (using `:map <C-i>`) I noticed that I had it mapped to `snippy-cut-text`. But I didn't do that. `verbose` tells me the mapping is comming from my lua config. The relevant sections are:
```
local snippy = require('snippy')
snippy.setup({
    mappings = {
        is = {
            ["<Tab>"] = "expand_or_advance",
            ["<S-Tab>"] = "previous",
        },
        nx = {
            ["<Tab>"] = "cut_text",
        },
    },
})
```
and if it matters, cmp-snippy is also installed
```
local cmp = require('cmp')
cmp.setup({
    sources = cmp.config.sources({
        { name = 'snippy' },
    }),
    snippet = {
        expand = function(args)
            require('snippy').expand_snippet(args.body)
        end,
    }
})
```

So now I am wondering why `<C-i>` is being mapped to `snippy-cut-text`.
I've searched my whole nvim config directory for the strings that would create this mapping in VimL and Lua and could not find anything, so I'm wondering if this is perhaps a problem with snippy or cmp-snippy?
Thank you in advance!

**Comment by AurelWeinhold** [comment]
I think this might be because my terminal sends the same keycode for `<C-i>` and `<Tab>`, so nothing you can do about it. I'll probably just delete the normal mode mapping.

**Comment by dcampos** [comment]
Hi!

Yeah, `<C-i>` and `<Tab>` are the same in (Neo)vim, and I think you're right about it being a terminal limitation. So nothing to do about it, indeed.

I use `g<Tab>` as a normal mode mapping for `snippy-cut-text`, so that it does not override any mapping that I make frequent use of.
