### ISSUE TITLE
col value out of range

### ISSUE THREAD

**Issue by rhcher** [dcampos/nvim-snippy#47]
## Explain the issue
Sometimes some error messages like `col vlaue out of range` pop up.

## Steps to reproduce
 1. run `nvim -u vimrc.vim test.py`
 2. We can input like this
![image](https://user-images.githubusercontent.com/50723480/150630119-f5c06a00-883e-460a-98a5-cd8142f91c4a.png)

 3. Then we press `tab` key, and the snippt will be expanded.
![image](https://user-images.githubusercontent.com/50723480/150630157-4736476e-aec2-427d-9e54-3914c3b1946b.png)

 4. Then we go ahead and press the `tab` key to make the cursor jump to the comment.
![image](https://user-images.githubusercontent.com/50723480/150630409-68d7f72c-91f5-41d4-8f2a-57701c3fb9b4.png)
5. Type something random and when we type the second letter, an error message will pop up
![image](https://user-images.githubusercontent.com/50723480/150630209-6cd6d322-eb3c-412f-86c3-f01f5a16b8dc.png)

## Minimal working example
test.py
```python
def
```

## Minimal vimrc file
vimrc.vim
```vim

if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'dcampos/nvim-snippy'
Plug 'honza/vim-snippets'
call plug#end()
PlugInstall | quit

imap <expr> <Tab> snippy#can_expand_or_advance() ? '<Plug>(snippy-expand-or-advance)' : '<Tab>'
imap <expr> <S-Tab> snippy#can_jump(-1) ? '<Plug>(snippy-previous)' : '<S-Tab>'
smap <expr> <Tab> snippy#can_jump(1) ? '<Plug>(snippy-next)' : '<Tab>'
smap <expr> <S-Tab> snippy#can_jump(-1) ? '<Plug>(snippy-previous)' : '<S-Tab>'
xmap <Tab> <Plug>(snippy-cut-text)

lua << EOF
    require('snippy').setup({
        hl_group = 'Search',
    })
EOF

```

## Additonal information
nvim version: NVIM v0.7.0-dev+913-ge07a4b97f6
I can provide any other information if needed

**Comment by dcampos** [comment]
Hi, thanks for the very detailed issue description! I'm sure it will be helpful for debugging the problem.

I made a recent change to remove a placeholder's children when it is modified by hand, so it seems like this issue may have been caused by that change. I'll look into it as soon as possible.

**Comment by dcampos** [comment]
It should be working now. Please let me know if it still doesn't.
