### ISSUE TITLE
bad argument #1 to 'unpack' with Codi.vim plugin.

### ISSUE THREAD

**Issue by rhcher** [dcampos/nvim-snippy#48]
## Explain the issue
Sometimes some error messages like `bad argument #1 to 'unpack' ` pop up with Codi.vim plugin. I'm not sure if this is a bug in nvim-snippy. If not, I will close this and open issue in Codi.vim plugin.

## Steps to reproduce
 1. run `nvim -u vimrc.vim test.py`
 2. run command `:Codi`
 2. We can input like this
![image](https://user-images.githubusercontent.com/50723480/150630119-f5c06a00-883e-460a-98a5-cd8142f91c4a.png)

 3. Then we press `tab` key, and the snippt will be expanded.
![image](https://user-images.githubusercontent.com/50723480/150630157-4736476e-aec2-427d-9e54-3914c3b1946b.png)

 4. Then we type something random and error message will pop up.
![image](https://user-images.githubusercontent.com/50723480/150687011-95226650-b7a5-4360-8d4b-92079378f3d4.png)

## Minimal working example
test.py
```python
def
```

## Minimal vimrc file
vimrc.vim
```vim

if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'dcampos/nvim-snippy'
Plug 'honza/vim-snippets'
Plug 'metakirby5/codi.vim'
call plug#end()
PlugInstall | quit

imap <expr> <Tab> snippy#can_expand_or_advance() ? '<Plug>(snippy-expand-or-advance)' : '<Tab>'
imap <expr> <S-Tab> snippy#can_jump(-1) ? '<Plug>(snippy-previous)' : '<S-Tab>'
smap <expr> <Tab> snippy#can_jump(1) ? '<Plug>(snippy-next)' : '<Tab>'
smap <expr> <S-Tab> snippy#can_jump(-1) ? '<Plug>(snippy-previous)' : '<S-Tab>'
xmap <Tab> <Plug>(snippy-cut-text)

lua << EOF
    require('snippy').setup({
        hl_group = 'Search',
    })
EOF

```

## Additonal information
nvim version: NVIM v0.7.0-dev+914-g7717f38d3f
I test vsnip and it works well with Codi.vim plugin.
I can provide any other information if needed

**Comment by dcampos** [comment]
Hi, thanks once more for the detailed description. I believe this is a Codi.vim issue, because of this line in the `codi.vim` file:

https://github.com/metakirby5/codi.vim/blob/cf62681a4962ce1873e4b2a5e0bf401dcd42890f/autoload/codi.vim#L676

If you pass `-1` to `nvim_buf_clear_namespace`, all namespaces are cleared, including those used by other plugins. That seems to be the case here, so that the extmarks used by Snippy to track placeholders/tab stops are being removed by Codi.vim.

Changing that `-1` to `s:virtual_text_namespace` fixed the issue in my tests, but I don't know exactly how Codi.vim works, so I recommend opening an issue there and reporting the problem.

**Comment by rhcher** [comment]
Thank you for helping to research bugs not related to this plugin, I will close this issue and thanks again for your great work.

**Comment by telemachus** [comment]
I'm having this same problem, but I don't use Codi.vim.

Here's an example of what I'm seeing:

```
Error detected while processing CursorMovedI Autocommands for "<buffer=2>":
E5108: Error executing lua ...g/nvim/pack/bundle/start/nvim-snippy/lua/snippy/main.lua:416
: bad argument #1 to 'unpack' (table expected, got nil)
stack traceback:
        [C]: in function 'unpack'
        ...g/nvim/pack/bundle/start/nvim-snippy/lua/snippy/main.lua:416: in function '_che
ck_position'
        ...g/nvim/pack/bundle/start/nvim-snippy/lua/snippy/main.lua:242: in function '_han
dle_CursorMoved'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
Error detected while processing TextChangedI Autocommands for "<buffer=2>":
E5108: Error executing lua ...g/nvim/pack/bundle/start/nvim-snippy/lua/snippy/stop.lua:48:
 attempt to index local 'from' (a nil value)
stack traceback:
        ...g/nvim/pack/bundle/start/nvim-snippy/lua/snippy/stop.lua:48: in function 'get_b
efore'
        ...ig/nvim/pack/bundle/start/nvim-snippy/lua/snippy/buf.lua:208: in function 'fix_
current_stop'
        ...g/nvim/pack/bundle/start/nvim-snippy/lua/snippy/main.lua:232: in function '_han
dle_TextChanged'
        [string ":lua"]:1: in main chunk
```

Once these errors start, my only option seems to be to quit and restart Neovim.

Perhaps another plugin is to blame (as in this issue), but I'm not sure how to debug my situation (shy of removing all my plugins and adding them back one by one). Any suggestions would be great, though I understand that you may not have any clues either. (I'll work on creating a minimal test case and then maybe open a new bug.)
