### ISSUE TITLE
Shell snippet for `$`

### ISSUE THREAD

**Issue by cryptomilk** [dcampos/nvim-snippy#51]
Hi,

I would like to expand `$` to `${}` for shells (ft=sh):

```
snippet $
    ${$1}
```

That doesn't work. How do I achieve that?

It works fine for `%` -> `%{}` for ft=spec

**Comment by dcampos** [comment]
Hi!

Your snippet works fine for me as it is, although it would probably be a good idea to escape the dollar sign to prevent conflict with the tabstop marker:

```
snippet $
	\${$1}
```

If it still doesn't work for you, please try to reproduce it with the minimal config: https://github.com/dcampos/nvim-snippy/blob/master/misc/minimal.vim

**Comment by cryptomilk** [comment]
It works for me too. I see what's the exact error now. The expansion doesn't work inside of a string (`" "`). :thinking:

**Comment by dcampos** [comment]
I see what's happening. By default, Snippy tries to expand the whole string of characters before the cursor. The workaround for now is to use the `inword` option (see `:help snippy-usage-snippets` for more info):

```
snippet $ "Your description" i
	\${$1}
```

**Comment by dcampos** [comment]
Please let me know if it still doesn't work for you.
