### ISSUE TITLE
Variables aren't expanding

### ISSUE THREAD

**Issue by ObserverOfTime** [dcampos/nvim-snippy#56]
The only variable that works is `$VISUAL`.
I'm using nvim-cmp for autocompletion.
Am I missing something?

**Comment by dcampos** [comment]
Currently the only variable recognized in SnipMate-style (`*.snippet(s)`) snippets is `$VISUAL`, indeed. This is backwards compatible with SnipMate, but I don't think it shouldn't be possible to expand LSP/TextMate variables also, by changing the parser to allow it.
