### ISSUE TITLE
Show completion menu when a prefix matches multiple triggers

### ISSUE THREAD

**Issue by rsmith31415** [dcampos/nvim-snippy#58]
Maybe this is already an option, but I haven't been able to figure out how to show the completion menu with several completions without having to write the entire trigger. 

For example, suppose you have several snippets with the same prefix `:` (e.g. `:check:`, `:arrow:` and other unicode symbols), so you may want to simply type `:<Tab>` and show all of the relevant triggers in a completion menu. Is this possible? I noticed there is `snippy.get_completion_items()`, but I don't think it is possible to use it (Unknown function: snippy#get_completion_items)

Thanks!

**Comment by dcampos** [comment]
Hi! If you don't use a completion manager like nvim-cmp, there's the `snippy.complete()` function. I don't use it myself currently, but it seems to be working:

![image](https://user-images.githubusercontent.com/68250/165014780-54f0fe02-d2ed-48b0-b880-1c8b6a4e74dd.png)

To create an insert mode mapping for it, you can try the following command (Vimscript):

```vim
inoremap <silent> <c-r><tab> <cmd>lua require('snippy').complete()<cr>
```

In Lua:

```lua
vim.keymap.set('i', "<c-r><tab>", "<cmd>lua require('snippy').complete()<cr>", { silent = true })
```

BTW, `snippy.get_completion_items()` is just for getting the completion items; it doesn't show a completion menu.

**Comment by rsmith31415** [comment]
Hi @dcampos 

Excellent! Your solution works flawlessly. I didn't know I had to use `require('snippy')` to make it work in that context. The only minor issue is that after selecting an option from the menu (`<C-y>`), pressing another tab to expand the snippet doesn't work when the snippet is set to "Autotrigger". In such instances, it is necessary to go back one character and type it again:

https://user-images.githubusercontent.com/599274/165023206-54d32907-e460-4c13-b399-f53cccf7a0ad.mp4

As I said, it is really small inconvenience. In fact, I disabled my snippets with autotrigger because it is not a problem to trigger the snippet manually with `<Tab>`  at the end, but I thought you should know about this edge case.

Thanks!

**Comment by dcampos** [comment]
Hmm, I realize my answer was missing an important detail. To automatically expand the snippet upon completion, you can set up an autocmd like this:

```vim
augroup snippy_complete_done
    autocmd!   
    autocmd CompleteDone * lua require 'snippy'.complete_done()
augroup END
```

**Comment by rsmith31415** [comment]
Thanks! That's a good solution.
