### ISSUE TITLE
Is there any plans to support vscode snippets?

### ISSUE THREAD

**Issue by ikalnytskyi** [dcampos/nvim-snippy#62]
Is there any plans for this project to support vscode-style snippets? While I agree that snipmate syntax is much friendly when it comes to writing snippets, I personally found that existing collection, [rafamadriz/friendly-snippets](https://github.com/rafamadriz/friendly-snippets), is better than [honza/vim-snippets](https://github.com/honza/vim-snippets). The former, unfortunately, maintains snippets using vscode syntax.

**Comment by dcampos** [comment]
I have considered adding support for vscode snippets in the past, but never felt motivated, as I tend to not use snippet repositories and create all my snippets in the SnipMate format. Preferring friendly-snippets over vim-snippets for pre-built snippets seems like a good argument for supporting them, though. But personally I don't have a plan to implement it in the near future.

**Comment by stormc** [comment]
Maybe [snippet-converter.nvim](https://github.com/smjonas/snippet-converter.nvim) can be utilized w/o adding suchlike functionality into nvim-snippy itself?

**Comment by dcampos** [comment]
> Maybe [snippet-converter.nvim](https://github.com/smjonas/snippet-converter.nvim) can be utilized w/o adding suchlike functionality into nvim-snippy itself?

Sure. I was thinking about that solution too. I tried it and found some issues with the generated SnipMate snippets, which I've reported there. Let's hope for them to be fixed, so that there will be no need to duplicate the effort here.

**Comment by dcampos** [comment]
I've added an [example config](../wiki/Loading-VSCode-snippets) for using SnippetConverter to convert VSCode-like snippets to the snipmate format, which can then be loaded by Snippy. In case someone feels up for the task of adding the functionality directly to Snippy, I think we can reopen this issue.
