### ISSUE TITLE
List all available snippets outside of completion engine

### ISSUE THREAD

**Issue by tiagoprn** [dcampos/nvim-snippy#65]
Hello again!

I searched your documentation, but I didn't find what I will just describe, so sorry if I misunderstood it. 

Is there a function/command I could map on my configuration to have a list of all available snippets on the current filetype? If so, could you point me what is its' name? 

E.g. of what I am looking for:

`nnoremap <silent> <leader>sl <cmd>lua require'snippy'.list_snippets()<CR>| " (snippy) list snippets for current filetype`

**Comment by dcampos** [comment]
Currently there is no way to list all available snippets in the current scope, I'm afraid. A completion engine or even the `snippy.complete()` function (see #58) are your best bet.

The problem with listing all snippets is that there is no good interface for listing/filtering in default Neovim, without using an external plugin like FZF or Telescope. A plugin like [fhill2/telescope-ultisnips.nvim](https://github.com/fhill2/telescope-ultisnips.nvim) should be relatively easy to implement for Snippy.

**Comment by tiagoprn** [comment]
Mapping `snippy.complete()`, as you suggested on the linked issue, is enough for my use case. Thank you very much for point it out!
