### ISSUE TITLE
Regex transformed tabstop are expanded if it occurs before its source tabstop

### ISSUE THREAD

**Issue by bjin** [dcampos/nvim-snippy#66]
It seems that currently, only the first occurrence of specified tabstop will be expanded, even if it's a regex transformed tabstop of a latter (real) one.

```snip
snippet readint
	scanf("%d${1/[^,]*,[^,]*/%d/g}", $1);
```

Here I'm trying to automatically generate `scanf()` format string for reading multiple `int`s in C/C++ (contains of multiple `%d`s) of arguments `$1`. However, snippy only tries to expand the first occurrence of `$1`, and it broke this snippet. Swapping these two occurrence of tabstop `$1` works fine as expected.

I think it doesn't really make sense to expand transformed tabstop in the first place, since its just a substitute of a real tabstop with user input.

EDIT 1: I could confirm this snippet works as expected with VSCode.

EDIT 2: `$1` set to `&a, &b, &c` will expand the snippet to `scanf("%d%d%d", &a, &b, &c);`

**Comment by bjin** [comment]
I did some quick hack to get this issue solved for my use case. But some more testing shows that it's not a proper fix, and it messed up the cursor positions completely. I just closed the PR for now.

Anyway, could you please take a look at this? Maybe for a proper fix that handles cursor positioning just fine.

**Comment by dcampos** [comment]
Thanks for reporting! Looks like the the cursor jumped before the tabstops were mirrored, so the position was just wrong and didn't get corrected. I've changed it to jump after the mirroring/transform is done, and also added a test.

**Comment by bjin** [comment]
Thanks for the fix!

Just in case someone else find it somehow useful, here is the final snippet I ended up with:
```snip
snippet readint
	scanf("${1/[^,]*,[^,]*/%d/g}"$1);$0
```

The previous version doesn't handle the case where there is no comma in `$1`.
