### ISSUE TITLE
j/k move cursor in selection mode instead of inserting letters j/k

### ISSUE THREAD

**Issue by Galicarnax** [dcampos/nvim-snippy#68]
Example case: I have a snippet for C++ `for` loop, which expands to
```cpp
for (int i = 0; i < counter; i++)
{

}
```
But when I `<Tab>` to `i` (with all three of them to be edited in the selection mode), and want to repalce it with `j`, my cursor moves down instead, extending the selection. The same happens with `k`, but this time cursor goes up one line. Other letters seem to work fine, i.e. I have no problem with replacing `i` with, e.g., `s`. I tried the same with almost all of other plugins disabled (including `nvim-cmp`), still behavior is the same. Franky, I am surprised to see that pressing letter keys in the `selection` mode works like in the `visual` mode (not replacing the selection).

**Comment by dcampos** [comment]
Do you have `j`/`k` mapped to something else in visual mode? If so, try changing any `v`-mappings (`vnoremap`, etc.) to `x`-mapping (`xnoremap`...). Example:

```vim
vnoremap <expr> j v:count ? 'j' : 'gj' 
vnoremap <expr> k v:count ? 'k' : 'gk'
```

Change to:

```vim
xnoremap <expr> j v:count ? 'j' : 'gj' 
xnoremap <expr> k v:count ? 'k' : 'gk'
```

See `help Select-mode-mapping` for how mappings work in select mode. In short, select mode inherits any visual mappings when `v` mappings are used; use `x` if you don't want this to happen.

**Comment by Galicarnax** [comment]
That's it, I had exacly these `vnoremap`s, and I've changed them per your suggestion. Now it works as expected. Thank you.
I was confused by the fact that when using UltiSnips, I didn't  observe this behaviour (all other configs being equal) - `j`/`k`/ isnerted letters instead of moving cursor in `select` mode. Probably, Ultisnips somehow handles this situation.

**Comment by dcampos** [comment]
I'm glad it helped!
