### ISSUE TITLE
honza/vim-snippets Works But My Custom Vim Snippets do Not Work

### ISSUE THREAD

**Issue by amarakon** [dcampos/nvim-snippy#74]
### Description

I am using honza/vim-snippets for a bunch of sensible default snippets. But I want to change the default C snippets. So I created a file `~/.config/nvim/snippets/c.snippets`, and changed some snippets, but the changes do not apply.

### Steps to Reproduce

1. git clone honza/vim-snippets into `~/.local/share/nvim/site/pack/default/start`
2. copy honza/vim-snippets/snippets/c.snippets into `~/.config/nvim/snippets`
3. change some snippets

### Expected Result

The changed I made to the snippets apply

### Actual Result

It still uses honza's vim snippets

**Comment by dcampos** [comment]
Hi! You can define a higher priority for your snippets, so they will override snippets from honza/vim-snippets.

Put something like this at the top of your custom snippets file (like `~/.config/nvim/snippets/c.snippets`):

```
priority 100

# Your custom snippets...
```

Please let me know if it still doesn't work.

**Comment by amarakon** [comment]
Yes, that works, thanks. A priority of 2 did the trick.
