### ISSUE TITLE
Custom expand options

### ISSUE THREAD

**Issue by cnrrobertson** [dcampos/nvim-snippy#75]
### Problem Statement

I was wondering if it would be possible to use custom options (aside from the w,i,b,A that are included). I'm imagining defining the option letter along with a lua function in a table in the `setup()` call.

I should mention that I have a very specific use case in mind which is to only autoexpand certain snippets when in a "math" context in Latex. It makes it easy to define autosnippets related to math that don't expand while you are writing the body of the document. See [here](https://castel.dev/post/lecture-notes-1/) for examples.

### Ideas or possible solutions

From a quick look at your source, I think it could be as simple as checking for a letter that is not i,w,b,A, including it in `option`, then looking up the corresponding function on expand.

It could also plug into `can_expand` as a conditional.

### Alternatives you have considered

Ultisnips has this functionality as [custom contexts](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L1477) and Luasnip has this as [condition](https://github.com/L3MON4D3/LuaSnip/blob/master/doc/luasnip.txt#L194).

**Comment by dcampos** [comment]
Fixed by #87.
