### ISSUE TITLE
Nested expansion sometimes doesn't work

### ISSUE THREAD

**Issue by dcampos** [dcampos/nvim-snippy#80]
### Description

It looks like there is some issue when trying to expand a snippet from inside another.

First snippet:

```
snippet s1
	local ${1:var} = ${0:value}

```
Second snippet:

```
snippet s2
	require(${1:modname})
```

### Steps to Reproduce

1. Expand the first snippet.
2. Jump to the second tab stop.
3. Expand the second snippet.

### Expected Result

The `modname` placeholder gets selected.

### Actual Result

The placeholder is skipped and the cursor jumps to the end of the line.

**Comment by mg979** [comment]
Commenting out this block fixes it, but it surely breaks something else

https://github.com/dcampos/nvim-snippy/blob/1860215584d4835d87f75896f07007b3b3c06df4/lua/snippy/buf.lua#L103-L109
