### ISSUE TITLE
Loading more snippets on demand

### ISSUE THREAD

**Issue by antonk52** [dcampos/nvim-snippy#9]
Hi, it is nice to see a snippet plugin that does not require external dependencies.

I am wondering if there is a way to load additional snippets on demand. Ie if you have snippets available for certain filetype and based a condition you would like to add more snippets for current buffer only. A practical example for this feature can be test files. Where normal snippets can be used. But you could also have test specific snippets. I know that UltiSnips have a command `UltiSnipsAddFiletypes` that allows to add additional snippets from a different filetype. Is something similar to this available or could be implemented with snippy?

Thanks

**Comment by dcampos** [comment]
I've added a way to customize which snippets are loaded for a specific buffer/filetype. You can use the `snippy.setup()` for that:

```lua
    require('snippy').setup({
        scopes = {
            lua = function(scopes)
                -- Add `busted.snippets` for Lua files matching `*spec.lua$`
                if vim.api.nvim_buf_get_name(0):find('_spec.lua$') then
                    table.insert(scopes, 'busted')
                end
                return scopes
            end,
        end
    })
```

It's also possible to setup scopes by buffer using an `autocmd`:

```vim
    autocmd BufRead,BufNewFile *_spec.lua lua require('snippy').setup_buffer(0,
        \ { scopes = { '_', 'lua', 'busted' } })
```
