### ISSUE TITLE
Strange conflict with miniyank

### ISSUE THREAD

**Issue by raine** [dcampos/nvim-snippy#91]
### Description

With [`miniyank`](https://github.com/bfredl/nvim-miniyank), I have `p` mapped to `<Plug>(miniyank-autoput)`:

```
:map p
  p             <Plug>(miniyank-autoput)
```

Then, for example when completing this snippet:

```
snippet fn "Function definition"
	fn ${1:function_name}(${2})${3} {
		${0}
	}
``` 

and pressing `p` to type the first character of `function_name`, neovim appears to run the `miniyank-autoput` command instead of inserting the `p` character.

See this demo where I first yank `foobar` and then complete the snippet with `fn<tab>`, and insert `p` as the first character of the function name, and then press `p` repeatedly.

Every other character works normally, and even `p` works if I type something else as the first character of the function.

![Kapture 2022-12-11 at 15 57 03](https://user-images.githubusercontent.com/11027/206907925-0d9c08ab-aef0-4b40-b5f1-38c0dd87b332.gif)

If I unmap `p`, the problem goes away.

Any ideas? Thank you!

### Steps to Reproduce

See description.

### Expected Result

See description.

### Actual Result

See description.

**Comment by raine** [comment]
Creating the miniyank mapping for normal mode (`nmap`) only seems to have fixed the issue for me.

I'm not sure why the author recommends `map` in the README, as I don't think the plugin is used in insert mode.

Perhaps this is the correct fix, if so, feel free to close.

**Comment by dcampos** [comment]
> I'm not sure why the author recommends map in the README, as I don't think the plugin is used in insert mode.

`map` maps in normal, visual (which includes select) and operator-pending modes. In your case, nvim is in select mode when you press `p`, so this seems to be the problem.
